### ISSUE TITLE
Update use plugin

### ISSUE THREAD

**Issue by TheJson** [gustavomazzoni/cordova-plugin-tesseract#1]
Hello, I want to use this plugin but with this documentation it isn't work. Can you update it? Thanks.

**Comment by gustavomazzoni** [comment]
Hi!

Could you be more specific? What errors/issues are you facing? Can you copy and paste it here?

**Comment by TheJson** [comment]
This is my steps:
1) Download your project/plugin and install it with --> ionic plugin add local-path
2) Add platform android --> ionic platform add android
3) Copy and paste tess-two folder to .../platforms/android/ download from this url --> https://github.com/rmtheis/tess-two
4) Now I do --> ionic build android

I obtain this error:
Project with path ':tess-two' could not be found in root project 'android'.

Can you tell me how can use this plugin? Thanks

**Comment by gongsy945** [comment]
Error:(4, 0) Plugin with id 'com.github.dcendents.android-maven' not found.
~/platforms/android/tess-two/build.gradle

**Comment by TheJson** [comment]
@gongsy945 are you able to use the plugin?

**Comment by gustavomazzoni** [comment]
Hi, guys. I'm very busy at the moment, that's why I didn't reply sooner. But I am planning to help you out next week, ok?!
Also, feel free to fork the project and suggest some changes.

**Comment by TheJson** [comment]
Hi @gustavomazzoni are there news? Can you help us?

**Comment by gustavomazzoni** [comment]
Hi guys, I didn't forget you. I'm very busy at the moment.
This is an open source project, so feel free to fork it.
As soon as I'm free I will work on your request as well.

Em dom, 28 de ago de 2016 09:57, TheJson <notifications@github.com>
escreveu:

**Comment by gustavomazzoni** [comment]
@TheJson, @gongsy945 please try again! Follow the new instructions on README.md and it will work.

Please, give me a feedback. I will wait for some days before closing this issue.
