### ISSUE TITLE
Failed to read bitmap

### ISSUE THREAD

**Issue by naomipol** [gustavomazzoni/cordova-plugin-tesseract#17]
When calling `TesseractPlugin.recognizeText` I get this error: "Failed to read bitmap."
any clue what's the problem here?

log:
```
I/Tesseract(native)(30577): Initialized Tesseract API with language=eng
E/ReadFile(30577): Bitmap must be non-null
V/TesseractPlugin(30577): Exception in Execute:Failed to read bitmap
```

The problem is that the created bitmap is null and I don't know why.
Using Ionic2 with Angular2 and have the exact code as written in the readMe
Thanks for any help!!

**Comment by naomipol** [comment]
Found it!
I sent to recognizeText the imageData string with this prefix: `"data:image/jpeg;base64,"`
so the string couldn't be decoded correctly with the Base64 decoder and the bitmap returned null.

**Comment by yuliantosb** [comment]
@naomipol I get a same error here? Should I remove prfeix "data:image/jpeg;base64" ? but if I remove that, I stuck in 
`V/TesseractPlugin: calling baseApi.getUTF8Text()`
and debug is never end, please help me, I'm begging you

**Comment by rg777** [comment]
Any update on this issue?

**Comment by futurestar001** [comment]
I met the same issue. Any update on this issue? I'd appreciate the solution.

**Comment by futurestar001** [comment]
I tried of both adding "data:image/jpeg;base64," and removing "data:image/jpeg;base64,", both return the same issue "Failed to read bitmap" .

**Comment by merbin2012** [comment]
Same here. Hello, admin are you here?
