### ISSUE TITLE
nice plugin! could you add some sample code to use this plugin through the camera

### ISSUE THREAD

**Issue by coolara** [gustavomazzoni/cordova-plugin-tesseract#2]
could you add some sample code to use this plugin through the camera

**Comment by gustavomazzoni** [comment]
Hi, @coolara . I'm very busy at the moment, that's why I didn't reply sooner. But I am planning to help you out next week, ok?!

**Comment by coolara** [comment]
thank you

**Comment by sasikumarm** [comment]
Hi @gustavomazzoni , Please add the sample code to use your plugin through files and camera.

**Comment by coolara** [comment]
I want to know how much  accuracy it is

**Comment by gustavomazzoni** [comment]
Hi @sasikumarm! I've just added info on how to use this plugin on the README. You can find it on [Usage section](https://github.com/gustavomazzoni/cordova-plugin-tesseract#usage).
