### ISSUE TITLE
Update 2.4 in README.md

### ISSUE THREAD

**Issue by kartagis** [gustavomazzoni/cordova-plugin-tesseract#21]
Hello,
2.4 says to include tess-two in `project-root/platforms/android/cordova/lib/build.js`, but there are no such lines in it. It seems to be `project-root/platforms/android/cordova/lib/builders/GradleBuilder.js`, and `projectPath` seems to be `this.root`. I can provide a PR if you want.

**Comment by gustavomazzoni** [comment]
Hi @kartagis,
Sure, please submit a PR.
