### ISSUE TITLE
iOS build problem

### ISSUE THREAD

**Issue by Darkoon** [gustavomazzoni/cordova-plugin-tesseract#29]
Hey! 
Trying to use your plugin in ionic 2 on iOS but after installing pod I encountered problem: 
```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

I tried everything like reinstalling pod, updating cocapods etc. But the problem persists. 

I found out that there is a script in Xcode project Build Phases named `[CP] Check Pods Manifest.lock` with contents: 
```sh
diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
if [ $? != 0 ] ; then
   echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." > &2
   exit 1
fi
```

There is clearly some problem with `PODS_PODFILE_DIR_PATH` and `PODS_ROOT` because files `Podfile.lock` and `Manifest.lock` exists in locations: `platforms/ios/Podfile.lock`, `platforms/ios/Pods/Manifest.lock`.

After manually editing script to point to correct paths and running `ionic build ios` there is another error: 

```
/platforms/ios/DemoApp/Plugins/cordova-plugin-tesseract/claseAuxilar.h:12:9: fatal error: 'TesseractOCR/TesseractOCR.h' file not found
```

As I found there is Pod named TesseractOCRiOS installed instead of TessaractOCR. When I edited claseAuxilar.h file using `TesseractOCRiOS/TesseractOCR.h`,error still persisted in CLI, but xCode build managed to get over it and then prompted error in `TesseractPlugin.m` file. 
```
No visible @interface for 'CDVPluginResult' declares the selector 'toErrorCallbackString:'
```
 in lines 75 and 84 of TesseractPlugin.m.  
After fixing this problem with my own cordova plugin result handling, there is Linker Error:

```
Library not found for -lTesseractOCRiOS
```

Is there any option to easily build and run ionic project with this plugin? Is there any chance to not use cocoa pods? How can I actually get this plugin to work on ios? 

Thanks in advance

**Comment by Darkoon** [comment]
I managed to do a little workaround by manually compiling `TesseractOCR.framework` file and including it in cordova/ionic project.  There is xcode project in [TesseractOCRiOS repository](https://github.com/gali8/Tesseract-OCR-iOS) which you can compile to create your own `.framework` file.

**Comment by willowTank** [comment]
Hello Darkoon.
Thanks for your explain. I meet such issue. but I haven't solved this issus yet.
How Can I compile TesseractOCR.framework?

**Comment by hkcity1111** [comment]
Hi Darkoon,
Thanks for your explanation. I am not good at xcode. Would you share how to compile Tessaract0CR.framework too.

Thanks.

**Comment by Darkoon** [comment]
I compiled TesseractOCR.framework using source from [TesseractOCRiOS](https://github.com/gali8/Tesseract-OCR-iOS). Just open `Tesseract OCR iOS.xcodeproj` in Xcode and then build the `TesseractOCRAggregate` target.
