### ISSUE TITLE
Plugin with id 'com.github.dcendents.android-maven' not found.

### ISSUE THREAD

**Issue by gongsy945** [gustavomazzoni/cordova-plugin-tesseract#3]
Plugin with id 'com.github.dcendents.android-maven' not found.

~/platforms/android/tess-two/build.gradle:
import org.apache.tools.ant.taskdefs.condition.Os

apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: 'com.jfrog.bintray'

**Comment by gustavomazzoni** [comment]
Hi, @gongsy945 . I'm very busy at the moment, that's why I didn't reply sooner. But I am planning to help you out next week, ok?!
Also, feel free to fork the project and suggest some changes.

**Comment by gustavomazzoni** [comment]
Hi @gongsy945, please follow the new instructions on README.md. [Try this specific step](https://github.com/gustavomazzoni/cordova-plugin-tesseract#22-edit-your-projectplatformsandroidtess-twobuildgradle-and-replace-all-content-with) and it should solve your error.

Please, give me a feedback. I will wait for some days before closing this issue.
