### ISSUE TITLE
Can't compile the project in any other cloud compilers other than ionic

### ISSUE THREAD

**Issue by ravitdx** [gustavomazzoni/cordova-plugin-tesseract#9]
Hi,

There has been some problem compiling with ionic cli (for other plugins). so I am compiling in a cloud compiler which works perfectly for other plugins.but this plugin showing an error.

I suspect that because **claseAuxiliar.h** has a  **TesseractOCR/TesseractOCR.h** .I think you already mentioned to include the tesseract library.  But,the problem is I can't add files,because I am using a cloud compiler.

So,could you please add tesseract library in this project (if possible).  Atleast for ios. I think adding tesseract library in **src/ios** is enough (sorry if I am wrong).

**Comment by ravitdx** [comment]
Hi,
please give me a reply.My project mostly relying on this plugin.Is the above suggestion works?

I really need this plugin to work in a cloud compiler. BTW I am compiling the project in cocoon.io.

**Comment by gustavomazzoni** [comment]
Hi @ravitdx ,

Tesseract is a third library so I can't add its code here. But feel free to clone this project and make this change yourself.
